title: Project
pages:
  template: project
files: false
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  link:
    label: Link
    type:  text
  
    fields:
      image:
        label: Image
        type:  select
        options: images
      title:
        label: Title
        type:  textarea
      date:
        label: Date
        type:  date